### ISSUE TITLE
Replace TracedCallable.ThrowableSupport by guava Closer

### ISSUE THREAD

**Issue by sjoerdtalsma** [opentracing-contrib/java-globaltracer#4]
As suggested by @adriancole in #1:
> if suppression is a primary feature of this library, it should be tested like one. Guava is far more reviewed than this PR and more used than any library any of us here has created. Reusing some of this not only saves you work, but also it reduces the amount of stuff reviewers like me have to look at. Ex. I don't need to scrutinize tested code in guava.. it is one of the most reused libraries there is.
> 
> By reuse I mean you can literally copy/paste the inner types from Closer and cite them, if this feature is critical to you. Then, you can reuse the tests of them. Another alternative is to use something like shade to make closer bundled as an internal type. Then you wouldn't need to do much work except reference x.y.internal.Closer
> 
> Ex.
> https://github.com/google/guava/blob/master/guava/src/com/google/common/io/Closer.java
> https://github.com/google/guava/blob/master/guava-tests/test/com/google/common/io/CloserTest.java

I think we can let Maven pull in the actual guava Closer class by using the maven shader plugin.

**Comment by sjoerdtalsma** [comment]
Using a guava `Closer` requires Span to be `java.io.Closeable` (to comply with java 6 requirement).
This depends on fix https://github.com/opentracing/opentracing-java/pull/73 to be released.

**Comment by codefromthecrypt** [comment]
>
> Using a guava Closer requires Span to be java.io.Closeable (to comply
> with java 6 requirement).
> This depends on fix opentracing/opentracing-java#73
> <https://github.com/opentracing/opentracing-java/pull/73> to be released.
>
0.20.4 went out last week! coast is clear

**Comment by sjoerdtalsma** [comment]
Incorporated this in original PR #1.
