### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by sjoerdtalsma** [opentracing-contrib/java-globaltracer#5]
Follow discussion in https://github.com/opentracing-contrib/java-jaxrs/issues/3
Align with outcome of that issue.

**Comment by wu-sheng** [comment]
Seem good to go. Named `opentracing-java-globaltracer`?

**Comment by bhs** [comment]
I would argue against the opentracing prefix in the repo name (because it's redundant, that is). Github repo search is pretty broken and as such I'm skeptical that devs consider it their first choice for, well, searching.

**Comment by wu-sheng** [comment]
@bensigelman , see  your point.

**Comment by sjoerdtalsma** [comment]
As discussed, rename is not necessary for this repo.
