### ISSUE TITLE
Mechanism to handle "wrapper" Tracers

### ISSUE THREAD

**Issue by objectiser** [opentracing-contrib/java-globaltracer#7]
In some situations there will be a primary Tracer implementation, but potentially other Tracer proxies that will wrap the real Tracer, e.g. to intercept log events and report to other systems, or independently report metrics to another system.

It would be good if the global tracer could provide a mechanism to allow such a configuration to be established.

**Comment by wu-sheng** [comment]
Hope to add a new mechanism about wrap. Looking for any thoughts.

**Comment by objectiser** [comment]
One possibility would be for `Tracer` impls that wrap other tracers to implementation a common interface, but that would introduce a dependency from them to the `java-globaltracer`, which I don't think is desirable.

So another option is to use a convention, such as the wrapper `Tracer` impl provides a `setTracer` or `setWrappedTracer` method. The global tracer could then

* retrieve an instance of all available tracers
* verify that all but one provide a `setWrappedTracer` method
* set up a chain between all wrapping tracers ending with the non-wrapping tracer

Issues with this are:
* what happens if all tracers are 'wrapping' tracers - perhaps by default they all should default to wrapping `NoopTracer`, so it then does not matter which order they are chained
* this mechanism doesn't take into account order - but hopefully there are no cases where ordering would be important - e.g. one proxy tracer introduces new tags that may then be relevant to other tracers

**Comment by davidB** [comment]
In my experiment, I explicitly call GobalTracer.register with the stacked Tracer. I guess we can not define the order to stack WrapperTracer with ServiceLoader (who wrap/decorate who).

**Comment by wu-sheng** [comment]
- We can do it like this, at this moment:

```java
Tracer realTracer = GlobalTracer.get();
WrapperTracer wpTracer = new WrapperTracer(realTracer);
GlobalTracer.active(wpTracer);
```

- Or we can add a new `wrap/unwrap` API

```java
WrapperTracer wpTracer = new WrapperTracer();
GlobalTracer.withWrapper(wpTracer)

// WrapperTracer.class 
class WrapperTracer implements TracerWrapper

// TraceWrapper.class
class TracerWrapper {
    void wrap(Tracer realTracer);
}
``` 

---
Edited: Change some class names.

**Comment by sjoerdtalsma** [comment]
Initially the `GlobalTracer` tried to do too much (hence the 172 comments on #1).
I think this problem is also solvable with explicit registration without extending the API or the GlobalTracer.
The following code in your application initialization should work with some `WrappingTracer` that wraps a delegate:
```java
    Tracer delegate = ... // 'real' tracer here.
    GlobalTracer.register(new WrappingTracer(delegate));
```

The decision that the `GlobalTracer` will _not_ automatically work with multiple tracers is intentional.
The `ServiceLoader` result is only automatically used **if** there is only one `io.opentracing.Tracer` registered. With multiple `Tracer` implementations available, it becomes the responsibility of the application developer to explicitly register the one (s)he wants to use.

**Comment by sjoerdtalsma** [comment]
I concur that in this case it _is_ a little unfortunate that `GlobalTracer.get()` can't be used for the delegate.
However, that choice was made intentionally to make reasoning 'during initialization' possible and offer predictable behaviour to people using GlobalTracer.get() as constant value.

If there are more use cases such as this, it may be necessary to somehow expose the 'current' GlobalTracer implementation.

**Comment by sjoerdtalsma** [comment]
@objectiser 
>One possibility would be for Tracer impls that wrap other tracers to implementation a common interface, but that would introduce a dependency from them to the java-globaltracer, which I don't think is desirable.

I agree that's undesirable, but maybe we could relax the `ServiceLoader` requirement of a no-arg constructor to also allow a _single `Tracer` arg_ constructor? Then by-convention that could be our _wrapping tracer_ contract.
If we're very clear about the (lack of) prioritization among multiple wrapper tracers I think it may be feasible.

We **must** be very clear however that for such 'wrapping' tracers, _no assumptions whatsoever_ may be made about the wrapped tracers (except the OT API obviously).

Either way this adds complexity so we should be very clear in our documentation!

**Comment by objectiser** [comment]
@sjoerdtalsma Understand your points - I'm mainly thinking about it from the Java Agent perspective, where it would have no knowledge of potential 'wrapper' tracers, so if there was some automated (well documented) approach that would be useful.

**Comment by davidB** [comment]
From my young experience with tracer (Zipkin/Brave, Hawkular), none have zero constructor. In lot of case I have to configure it (backend service address, procotol,...).

Agent use GlobalTracer.get(), regardless how the Tracer was construct and registered as GlobalTracer.

**Comment by sjoerdtalsma** [comment]
@davidB 
> From my youg experience with tracer (Zipkin/Brave, Hawkular), none are zero constructor. In lot of case I have to configure it (backend service address, procotol,...).

Good point! I also replaced the automatic configuration by explicit initialization except for some trivial test services.

@objectiser 
>from the Java Agent perspective, where it would have no knowledge of potential 'wrapper' tracers

Just curious; do you have an example where the Java Agent needs to be more than a mere _user_ of the configured GlobalTracer?

**Comment by objectiser** [comment]
@davidB Hawkular APM has a default constructor

@sjoerdtalsma no examples currently.

**Comment by sjoerdtalsma** [comment]
One additional concern: the `java.util.ServiceLoader` will become more important with JDK 9 project jigsaw. Any custom reflection magic we add in that area _definitely_ needs to be well-tested with the JDK 9 pre-release.

**Comment by tedsuo** [comment]
Hi @objectiser. Given that globaltracer is in the process of migrating to core, any interest in getting a `java-tracewrapper` repo going?

**Comment by sjoerdtalsma** [comment]
I slept on this and would this be an option, using a `Tracer` -> `Tracer` function?
```java
    GlobalTracer.update(tracer -> new WrappingTracer(tracer));
```
We could implement the update thread-safe (~resolving race conditions by re-applying the function with the 'winner'~ with a write-lock) and (for the moment) don't need to touch the `ServiceLoader` concept.

**Comment by objectiser** [comment]
Hi @tedsuo , what functionality do you see in this `java-tracewrapper` project?

@sjoerdtalsma This would be an option if the application was in control of wrapping the tracer, but wouldn't solve the case where we wanted the wrapping to be handled automatically without the app being aware.

**Comment by sjoerdtalsma** [comment]
@objectiser We agree. 
I would like to separate the concerns of the required API change to the globaltracer and 'auto-registering' wrapper feature (which I think is a smaller concern).
Having the 'update' api extension, you could (for example)
- provide some 'memento identity function' to get at the underlying Tracer in a thread-safe way while keeping this complicated enough to keep thread-safety and control within the globaltracer.
- support a java-globaltracer-wrapper add-on module that defines a TracerWrapper interface and initialization code that automatically picks up wrappers, orders them by some prioritization strategy and updating the globaltracer with them.
- .. uses that we cannot yet foresee.

I actually prefer the `update` api to some `getDelegateTracer` to expose the underlying Tracer. I think this helps in encouraging people to stick to the OpenTracing API and can be implemented in a thread-safe manner.

**Comment by objectiser** [comment]
@sjoerdtalsma Ok sounds good.

**Comment by bhs** [comment]
One other thought from the peanut-gallery: there are two basic categories of wrapping use-cases:

1. Actually `tee`ing off to two separate fully-featured Tracer impls
1. Just getting callbacks about certain Span lifecycle things, perhaps for integration with conventional logging or metrics systems (see https://github.com/opentracing/opentracing-go/pull/135 for context)

I'm not saying that either is better or worse, but they are different... namely, the latter can be done more efficiently than the former since it doesn't care about meddling with inject/extract or SpanContext.

**Comment by davidB** [comment]
java-loggertracer include support for point 2 (callbacks about certain Span
lifecycle) via Reporter.

**Comment by tedsuo** [comment]
@objectiser just saw your comment. I was proposing a separate repo for working on the Wrapper component, since it is essentially independent from global tracer and possibly there are questions could stand real world use as a contrib project before merging, much like the path the Global Tracer took. Not sure what our policy is on that, but at any rate it does not seem that necessary to me any more.

**Comment by sjoerdtalsma** [comment]
@objectiser @tedsuo @davidB Please have a look at [Bens comment in the 'move' PR](https://github.com/opentracing/opentracing-java/pull/109#discussion_r107334092) where he prefers _less_ complexity in the `GlobalTracer` and proposes a _register-once_ semantic and no `update()` method.
Could you make the case for adding this feature there (in that PR) if you feel strongly about it?

**Comment by objectiser** [comment]
Due to the potential implications of updating the tracer after initial use, I'm currently in favour of the register-once approach. This would work fine if the app is in control of initialising the tracer explicitly, as it can decide if/which `WrapperTracer` it uses. However it would not allow a `WrapperTracer` to be used with implicit initialisation via the `ServiceLoader` - maybe we have to live with this, unless a differ implicit mechanism is used.

Possibly the implicit initialisation strategy is the thing that should be loaded via the `ServiceLoader`? So rather than service load `Tracer`, load a `TracerResolver` (or `TracerProvider`) instead? So the decision about how the tracer is implicitly initialized is not dictated by the GlobalTracer.

**Comment by sjoerdtalsma** [comment]
In PR https://github.com/opentracing/opentracing-java/pull/109 the GlobalTracer has been reduced to core `register` / `get` behaviour without automatic resolution.

Would it be useful to start a separate `java-tracerresolver` project containing the existing `ServiceLoader` functionality and add support for wrappers?

**Comment by objectiser** [comment]
That would be fine with me, and I guess this repo would be deprecated?

Another option would be that this repo changes to become contributions/extensions for the core globaltracer - so contains tracerprovider and any other globaltracer related capabilities?

**Comment by sjoerdtalsma** [comment]
@objectiser I intended to deprecate the current `GlobalTracer` implementation to redirect to the `opentracing-util` version (after its merge + release) and release one last redirecting version.

However, there's probably no need to hurry in coming up with a new name, we can always wait for things to settle first in the main java repo.

**Comment by objectiser** [comment]
@sjoerdtalsma Although would be good to have equivalent functionality as now, so would prefer if we had something like tracerresolver+serviceloader impl available soon, so I'm +1 for `java-tracerresolver`

**Comment by objectiser** [comment]
@sjoerdtalsma Now the GlobalTracer has been relocated, will you be kicking off the `java-tracerresolver` project? Or does it make sense to have a `TracerResolver` API and default service loader based impl is core utils?

**Comment by sjoerdtalsma** [comment]
@objectiser I may if I find some time which is in short supply lately 😉.
It won't be before the weekend though.

**Comment by sjoerdtalsma** [comment]
@objectiser If you can spare some time, could you please take a look at [sjoerdtalsma/java-tracerresolver](https://github.com/sjoerdtalsma/java-tracerresolver) before I request a new 'contrib' project?

**Comment by objectiser** [comment]
@sjoerdtalsma Looks good. Two questions:

1) Do you think this would be better in the core util package rather than a separate repo? @bhs Thoughts?

2) How do you see dealing with wrapper tracers in conjunction with this `TracerResolver` mechanism? One option would be to just let the app obtain the tracer via this mechanism, wrap it and then set in the `GlobalTracer` - which may be fine, but wouldn't deal with the case where we just wanted to provide the wrapped tracer as another service loadable dependency. This shouldn't impact getting the tracer resolver merged - but just wondering if you had any thoughts.

**Comment by sjoerdtalsma** [comment]
@objectiser 
Re 1; maybe we should let it mature in contrib first before considering it for core util?
Re 2; we can add a `wrapper` subpackage to the tracerresolver that resolves TracerWrapper instances and automatically applies them to resolved tracers. However, it may be prudent to gather some feedback on the core 'resolving' thing first.

A major lesson I learned from contributing to OpenTracing is the power of review by many eyes :wink:

**Comment by objectiser** [comment]
@sjoerdtalsma Fine with me on both points.

**Comment by sjoerdtalsma** [comment]
Closing this issue as it has been overtaken by the move to [opentracing-java](https://github.com/opentracing/opentracing-java/tree/master/opentracing-util) and the new [java-tracerresolver](https://github.com/opentracing-contrib/java-tracerresolver/pull/1) contrib module.
